<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
		xmlns:xs ="http://www.w3.org/2001/XMLSchema"
		version="3.0"
		>

  <!-- xqxml-to-callgraph-tot.xsl:  quick and dirty stylsheet to 
       read XML representation of XQuery module produced by
       xquery-31.xquery and write out a dot file with a 
       call graph.
  -->

  <xsl:output method='text'/>

  <xsl:template match="/">
    <xsl:text>digraph calls {&#xA;</xsl:text>
    <xsl:text>// autogenerated by xqxml-to-callgraph-dot ...&#xA;&#xA;</xsl:text>
    <xsl:apply-templates select="//FunctionDecl"/>
    <xsl:text>&#xA;}</xsl:text>
  </xsl:template>

  <xsl:template match="FunctionDecl">
    <xsl:variable name="caller-label"
		  as="xs:string"
		  select="normalize-space(EQName)"/>
    <xsl:variable name="caller"
		  as="xs:string"
		  select="translate($caller-label, ':-', '__')"/>
    
    <xsl:text>  </xsl:text>
    <xsl:value-of select="$caller"/>
    <xsl:text> [label="</xsl:text>
    <xsl:value-of select="$caller-label"/>
    <xsl:text>"];&#xA;</xsl:text>
    
    <xsl:apply-templates select="descendant::FunctionCall">
      <xsl:with-param name="caller" select="$caller"/>
    </xsl:apply-templates>
  </xsl:template>
  

  <xsl:template match="FunctionCall">
    <xsl:param name="caller" as="xs:string"/>
    <xsl:variable name="callee-label"
		  as="xs:string"
		  select="normalize-space(FunctionEQName)"/>
    <xsl:variable name="callee"
		  as="xs:string"
		  select="translate($callee-label, ':-', '__')"/>
    <!--
    <xsl:message>
      <xsl:value-of select="$callee-label"/>
      <xsl:text> as </xsl:text>
      <xsl:value-of select="$callee"/>
    </xsl:message>
    -->

    <xsl:text>  </xsl:text>
    <xsl:value-of select="$callee"/>
    <xsl:text> [label="</xsl:text>
    <xsl:value-of select="$callee-label"/>
    <xsl:text>"];&#xA;</xsl:text>
    
    <xsl:text>  </xsl:text>
    <xsl:value-of select="$caller"/>
    <xsl:text> -> </xsl:text>
    <xsl:value-of select="$callee"/>
    <xsl:text>;&#xA;</xsl:text>
  </xsl:template>
</xsl:stylesheet>
